# Generated by Django 3.0.3 on 2020-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='Delhi', max_length=25),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default='', max_length=250),
        ),
    ]
