# Generated by Django 3.0.3 on 2020-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0002_auto_20200709_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor_id', models.CharField(max_length=10)),
                ('email', models.EmailField(default='null', max_length=35)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='null', max_length=35),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(default='Delhi', max_length=40),
        ),
    ]
