# Generated by Django 3.0.3 on 2020-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0003_auto_20200710_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(default='null', max_length=35)),
                ('subject', models.TextField(default='', max_length=250)),
                ('rating', models.CharField(max_length=25)),
            ],
        ),
    ]
