# Generated by Django 3.0.3 on 2020-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilian_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=6)),
                ('email', models.EmailField(default='null', max_length=35)),
                ('mobile_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField(default='', max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(default='Delhi', max_length=40)),
                ('country', models.CharField(default='India', max_length=5)),
                ('occupation', models.CharField(max_length=25)),
                ('family_members', models.IntegerField()),
            ],
        ),
    ]
