# Generated by Django 3.0.3 on 2020-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0006_auto_20200712_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='country',
            field=models.CharField(choices=[('India', 'India')], default='India', max_length=5),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='email',
            field=models.EmailField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='family_members',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default='female', max_length=6),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland')], default='Delhi', max_length=40),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=35),
        ),
    ]
