# Generated by Django 3.0.3 on 2020-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0008_auto_20200712_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilian_data',
            name='phone_no',
        ),
    ]
