# Generated by Django 3.0.3 on 2020-07-12 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0009_remove_civilian_data_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='aadhaar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
