# Generated by Django 3.0.3 on 2020-07-12 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0010_auto_20200712_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='mobile_no',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
