# Generated by Django 3.0.3 on 2020-07-12 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0011_auto_20200712_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='aadhaar_no',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
