# Generated by Django 3.0.3 on 2020-07-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0012_auto_20200712_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
