# Generated by Django 3.0.3 on 2020-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0013_remove_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
    ]
