# Generated by Django 3.0.3 on 2020-07-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0015_auto_20200712_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='aadhaar_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
