# Generated by Django 3.0.3 on 2020-07-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0017_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
