# Generated by Django 3.0.3 on 2020-07-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0019_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
