# Generated by Django 3.0.3 on 2020-07-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0020_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
