# Generated by Django 3.0.3 on 2020-07-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0021_register_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
