# Generated by Django 3.0.3 on 2020-07-17 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sankalan_app', '0022_auto_20200717_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Surveyor',
        ),
    ]
