# Generated by Django 3.0.3 on 2020-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0023_auto_20200718_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian_data',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
