# Generated by Django 3.0.3 on 2020-07-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0026_auto_20200718_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilian_data',
            options={'verbose_name_plural': 'Civilian Data'},
        ),
    ]
