# Generated by Django 3.0.3 on 2020-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0027_auto_20200719_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='aadhaar_no',
            field=models.IntegerField(unique=True),
        ),
    ]
