# Generated by Django 3.0.3 on 2020-08-01 11:06

import datetime
from django.db import migrations, models
import sankalan_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0028_auto_20200719_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('aadhaar_no', models.IntegerField(unique=True)),
                ('dob', models.DateField(validators=[sankalan_app.models.validate_date])),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('other', 'other')], default='female', max_length=6)),
                ('address', models.TextField(default='', max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland')], default='Delhi', max_length=40)),
                ('country', models.CharField(choices=[('India', 'India')], default='India', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Aadhaar Data',
            },
        ),
        migrations.CreateModel(
            name='Received_SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_no', models.IntegerField(unique=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Received SMS',
            },
        ),
    ]
