# Generated by Django 3.0.3 on 2020-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0029_aadhaar_data_received_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaar_data',
            name='email',
            field=models.EmailField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='aadhaar_data',
            name='mobile_no',
            field=models.IntegerField(default=''),
        ),
    ]
