# Generated by Django 3.0.3 on 2020-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0029_aadhaar_data_received_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='fname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='lname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
