# Generated by Django 3.0.3 on 2020-08-02 08:06

from django.db import migrations, models
import sankalan_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0030_auto_20200802_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[sankalan_app.models.validate_date]),
        ),
    ]
