# Generated by Django 3.0.3 on 2020-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0031_auto_20200802_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian_data',
            name='address',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='civilian_data',
            name='occupation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
