# Generated by Django 3.0.3 on 2020-08-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0032_auto_20200802_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaar_data',
            name='email',
        ),
    ]
