# Generated by Django 3.0.3 on 2020-08-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalan_app', '0033_remove_aadhaar_data_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaar_data',
            name='mobile_no',
        ),
    ]
